import { Category, Product, SiteSettings } from '../types';

export const DEFAULT_SETTINGS: SiteSettings = {
  general: {
    brand_name: 'VELORA',
    tagline: 'Haute Couture & Lifestyle',
    whatsapp: '94778005550',
    whatsapp_display: '0778005550',
    email: 'veloraofficialsrilanka@gmail.com',
    facebook_url: 'https://www.facebook.com/share/1JVfrLeoxE/',
    instagram_url: 'https://www.instagram.com/veloraofficialsrilanka?stkn=NWEzcGlkNmJ4Y2R2',
    currency: 'LKR',
    currency_symbol: 'Rs.',
    logo_url: '/velora-logo.svg',
  },
  bank_transfer: {
    bank_name: 'Commercial Bank of Ceylon',
    account_name: 'VELORA LIFESTYLE (PVT) LTD',
    account_number: '1000 4829 1190',
    branch: 'Colombo 07 / Main Corporate Branch',
    instructions: 'Please transfer or deposit the exact total amount to the account above. Then share your payment receipt or transfer screenshot on WhatsApp for instant confirmation.',
  },
  delivery: {
    islandwide_fee_lkr: 500,
    delivery_enabled: true,
    free_delivery_threshold_lkr: 0,
    estimated_days: '2-4 Business Days',
  },
  announcement: {
    enabled: true,
    text: 'ISLANDWIDE EXPRESS COURIER DELIVERY AVAILABLE • 100% AUTHENTIC QUALITY GUARANTEED',
    link: '',
  },
  hero: {
    title: 'DEFINING MODERN LUXURY',
    subtitle: 'Explore Haute Couture, Designer Eyewear & Artisanal Fragrances',
    cta_text: 'EXPLORE NEW ARRIVALS',
    cta_link: '/category/women',
    image_desktop: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=2000&auto=format&fit=crop',
    image_mobile: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
  },
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-women',
    name: 'WOMEN',
    slug: 'women',
    description: 'Contemporary haute couture, activewear, and everyday luxury essentials.',
    parent_id: null,
    sort_order: 1,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-w-tshirts', name: 'T-shirts', slug: 'women-t-shirts', parent_id: 'cat-women', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-w-polos', name: 'Polos', slug: 'women-polos', parent_id: 'cat-women', sort_order: 2, is_active: true, is_featured: false },
      { id: 'sub-w-crop', name: 'Crop tops', slug: 'women-crop-tops', parent_id: 'cat-women', sort_order: 3, is_active: true, is_featured: true },
      { id: 'sub-w-bras', name: 'Sports Bras', slug: 'women-sports-bras', parent_id: 'cat-women', sort_order: 4, is_active: true, is_featured: true },
      { id: 'sub-w-tanks', name: 'Tanks', slug: 'women-tanks', parent_id: 'cat-women', sort_order: 5, is_active: true, is_featured: false },
      { id: 'sub-w-leggings', name: 'Leggings', slug: 'women-leggings', parent_id: 'cat-women', sort_order: 6, is_active: true, is_featured: true },
      { id: 'sub-w-skirts', name: 'Skirts', slug: 'women-skirts', parent_id: 'cat-women', sort_order: 7, is_active: true, is_featured: false },
      { id: 'sub-w-shorts', name: 'Shorts', slug: 'women-shorts', parent_id: 'cat-women', sort_order: 8, is_active: true, is_featured: false },
      { id: 'sub-w-hoodies', name: 'Hoodies & Jackets', slug: 'women-hoodies-jackets', parent_id: 'cat-women', sort_order: 9, is_active: true, is_featured: true },
      { id: 'sub-w-jeans', name: 'Jeans', slug: 'women-jeans', parent_id: 'cat-women', sort_order: 10, is_active: true, is_featured: false },
      { id: 'sub-w-joggers', name: 'Joggers & Pants', slug: 'women-joggers-pants', parent_id: 'cat-women', sort_order: 11, is_active: true, is_featured: true },
    ],
  },
  {
    id: 'cat-men',
    name: 'MEN',
    slug: 'men',
    description: 'Precision-tailored streetwear, active compression, and modern minimalist wardrobe.',
    parent_id: null,
    sort_order: 2,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-m-tshirts', name: 'T-shirts', slug: 'men-t-shirts', parent_id: 'cat-men', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-m-shirts', name: 'Shirts', slug: 'men-shirts', parent_id: 'cat-men', sort_order: 2, is_active: true, is_featured: true },
      { id: 'sub-m-polos', name: 'Polos', slug: 'men-polos', parent_id: 'cat-men', sort_order: 3, is_active: true, is_featured: false },
      { id: 'sub-m-shorts', name: 'Shorts', slug: 'men-shorts', parent_id: 'cat-men', sort_order: 4, is_active: true, is_featured: true },
      { id: 'sub-m-tanks', name: 'Tanks', slug: 'men-tanks', parent_id: 'cat-men', sort_order: 5, is_active: true, is_featured: false },
      { id: 'sub-m-compressions', name: 'Compressions', slug: 'men-compressions', parent_id: 'cat-men', sort_order: 6, is_active: true, is_featured: true },
      { id: 'sub-m-hoodies', name: 'Hoodies & Jackets', slug: 'men-hoodies-jackets', parent_id: 'cat-men', sort_order: 7, is_active: true, is_featured: true },
      { id: 'sub-m-jeans', name: 'Jeans', slug: 'men-jeans', parent_id: 'cat-men', sort_order: 8, is_active: true, is_featured: false },
      { id: 'sub-m-joggers', name: 'Joggers & Pants', slug: 'men-joggers-pants', parent_id: 'cat-men', sort_order: 9, is_active: true, is_featured: true },
      { id: 'sub-m-underwear', name: 'Underwear', slug: 'men-underwear', parent_id: 'cat-men', sort_order: 10, is_active: true, is_featured: false },
    ],
  },
  {
    id: 'cat-accessories',
    name: 'ACCESSORIES',
    slug: 'accessories',
    description: 'Elevated lifestyle accessories, leather goods, and headwear.',
    parent_id: null,
    sort_order: 3,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-a-hats', name: 'Hats & Caps', slug: 'hats-caps', parent_id: 'cat-accessories', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-a-shoes', name: 'Shoes', slug: 'shoes', parent_id: 'cat-accessories', sort_order: 2, is_active: true, is_featured: true },
      { id: 'sub-a-slides', name: 'Slides', slug: 'slides', parent_id: 'cat-accessories', sort_order: 3, is_active: true, is_featured: false },
      { id: 'sub-a-jewel', name: 'Jewellery', slug: 'accessories-jewellery', parent_id: 'cat-accessories', sort_order: 4, is_active: true, is_featured: true },
      { id: 'sub-a-socks', name: 'Socks', slug: 'socks', parent_id: 'cat-accessories', sort_order: 5, is_active: true, is_featured: false },
      { id: 'sub-a-bottles', name: 'Bottles & Tumblers', slug: 'bottles-tumblers', parent_id: 'cat-accessories', sort_order: 6, is_active: true, is_featured: true },
      { id: 'sub-a-bags', name: 'Bags', slug: 'bags', parent_id: 'cat-accessories', sort_order: 7, is_active: true, is_featured: true },
      { id: 'sub-a-merch', name: 'Merch', slug: 'merch', parent_id: 'cat-accessories', sort_order: 8, is_active: true, is_featured: false },
    ],
  },
  {
    id: 'cat-cosmetics',
    name: 'COSMETICS',
    slug: 'cosmetics',
    description: 'Dermatological skincare, pure beauty formulas, and hair treatments.',
    parent_id: null,
    sort_order: 4,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-c-face', name: 'Face Care', slug: 'face-care', parent_id: 'cat-cosmetics', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-c-body', name: 'Body Care', slug: 'body-care', parent_id: 'cat-cosmetics', sort_order: 2, is_active: true, is_featured: true },
      { id: 'sub-c-hair', name: 'Hair Care', slug: 'hair-care', parent_id: 'cat-cosmetics', sort_order: 3, is_active: true, is_featured: false },
      { id: 'sub-c-toiletries', name: 'Toiletries', slug: 'toiletries', parent_id: 'cat-cosmetics', sort_order: 4, is_active: true, is_featured: false },
      { id: 'sub-c-men', name: 'Men Care', slug: 'cosmetics-men', parent_id: 'cat-cosmetics', sort_order: 5, is_active: true, is_featured: false },
      { id: 'sub-c-makeup', name: 'Makeup', slug: 'makeup', parent_id: 'cat-cosmetics', sort_order: 6, is_active: true, is_featured: true },
    ],
  },
  {
    id: 'cat-sunglasses',
    name: 'SUNGLASSES',
    slug: 'sunglasses',
    description: 'Polarized, UV400 artisanal eyewear crafted with lightweight metal and acetate.',
    parent_id: null,
    sort_order: 5,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-s-him', name: 'For Him', slug: 'sunglasses-for-him', parent_id: 'cat-sunglasses', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-s-her', name: 'For Her', slug: 'sunglasses-for-her', parent_id: 'cat-sunglasses', sort_order: 2, is_active: true, is_featured: true },
      { id: 'sub-s-unisex', name: 'Unisex', slug: 'sunglasses-unisex', parent_id: 'cat-sunglasses', sort_order: 3, is_active: true, is_featured: true },
      { id: 'sub-s-kids', name: 'Kids', slug: 'sunglasses-kids', parent_id: 'cat-sunglasses', sort_order: 4, is_active: true, is_featured: false },
      { id: 'sub-s-lovers', name: 'For Lovers', slug: 'sunglasses-lovers', parent_id: 'cat-sunglasses', sort_order: 5, is_active: true, is_featured: false },
    ],
  },
  {
    id: 'cat-perfumes',
    name: 'PERFUMES',
    slug: 'perfumes',
    description: 'Artisanal Eau de Parfum blends and international luxury fragrance collections.',
    parent_id: null,
    sort_order: 6,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-p-all', name: 'All Perfumes', slug: 'all-perfumes', parent_id: 'cat-perfumes', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-p-men', name: 'For Men', slug: 'perfumes-men', parent_id: 'cat-perfumes', sort_order: 2, is_active: true, is_featured: true },
      { id: 'sub-p-women', name: 'For Women', slug: 'perfumes-women', parent_id: 'cat-perfumes', sort_order: 3, is_active: true, is_featured: true },
      { id: 'sub-p-sets', name: 'Perfume Gift Sets', slug: 'perfume-gift-sets', parent_id: 'cat-perfumes', sort_order: 4, is_active: true, is_featured: false },
    ],
  },
  {
    id: 'cat-kids',
    name: 'KIDS & BABY',
    slug: 'kids-baby',
    description: 'Hypoallergenic soft toys, plush comfort sets, and newborn essentials.',
    parent_id: null,
    sort_order: 7,
    is_active: true,
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-k-toys', name: 'Soft Toys', slug: 'soft-toys', parent_id: 'cat-kids', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-k-baby', name: 'Baby Essentials', slug: 'baby-essentials', parent_id: 'cat-kids', sort_order: 2, is_active: true, is_featured: true },
    ],
  },
  {
    id: 'cat-jewellery',
    name: 'JEWELLERY',
    slug: 'jewellery',
    description: '18k gold plated chains, minimalist rings, and freshwater pearls.',
    parent_id: null,
    sort_order: 8,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-j-earrings', name: 'Earrings', slug: 'jewellery-earrings', parent_id: 'cat-jewellery', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-j-pendants', name: 'Pendants', slug: 'jewellery-pendants', parent_id: 'cat-jewellery', sort_order: 2, is_active: true, is_featured: true },
      { id: 'sub-j-necklaces', name: 'Necklaces', slug: 'jewellery-necklaces', parent_id: 'cat-jewellery', sort_order: 3, is_active: true, is_featured: true },
    ],
  },
  {
    id: 'cat-home',
    name: 'HOME',
    slug: 'home',
    description: 'Modern luxury home decor, ceramic dinnerware, and ambient scent diffusers.',
    parent_id: null,
    sort_order: 9,
    is_active: true,
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-h-dinner', name: 'Dinnerware', slug: 'dinnerware', parent_id: 'cat-home', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-h-fragrance', name: 'Home Fragrance', slug: 'home-fragrance', parent_id: 'cat-home', sort_order: 2, is_active: true, is_featured: true },
    ],
  },
  {
    id: 'cat-watches',
    name: 'WATCHES',
    slug: 'watches',
    description: 'Chronograph and sapphire crystal timepieces with stainless steel mesh bands.',
    parent_id: null,
    sort_order: 10,
    is_active: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-w-her', name: 'For Her', slug: 'watches-for-her', parent_id: 'cat-watches', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-w-him', name: 'For Him', slug: 'watches-for-him', parent_id: 'cat-watches', sort_order: 2, is_active: true, is_featured: true },
    ],
  },
  {
    id: 'cat-essentials',
    name: 'ESSENTIALS',
    slug: 'essentials',
    description: 'Luxury loungewear, satin robes, and intimate wellness pieces.',
    parent_id: null,
    sort_order: 11,
    is_active: true,
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=800&auto=format&fit=crop',
    subcategories: [
      { id: 'sub-e-robes', name: 'Robes', slug: 'robes', parent_id: 'cat-essentials', sort_order: 1, is_active: true, is_featured: true },
      { id: 'sub-e-sets', name: 'Matching Sets', slug: 'matching-sets', parent_id: 'cat-essentials', sort_order: 2, is_active: true, is_featured: true },
    ],
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Velora Monogram Heavyweight Oversized T-Shirt',
    slug: 'velora-monogram-heavyweight-oversized-t-shirt',
    item_code: 'VL-W-0101',
    brand: 'VELORA',
    category_id: 'cat-women',
    subcategory_id: 'sub-w-tshirts',
    description: 'Crafted from 280GSM pure combed cotton with double-needle drop shoulder construction. Features subtle golden micro-embroidery of the signature Velora monogram on the chest.',
    item_details: '• 100% Combed Heavy Cotton (280 GSM)\n• Pre-shrunk drop-shoulder fit\n• Gold thread embroidery detail\n• Machine wash cold, hang dry',
    normal_price_lkr: 5200,
    offer_price_lkr: 4400,
    stock: 45,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_best_seller: true,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Velora Monogram Heavyweight Oversized T-Shirt Front',
        sort_order: 0,
        is_primary: true,
      },
      {
        image_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Velora Monogram Heavyweight Oversized T-Shirt Back',
        sort_order: 1,
        is_primary: false,
      },
    ],
    options: [
      {
        name: 'Color',
        sort_order: 0,
        values: [
          { value: 'Obsidian Black', sort_order: 0 },
          { value: 'Ivory Cream', sort_order: 1 },
        ],
      },
      {
        name: 'Size',
        sort_order: 1,
        values: [
          { value: 'S', sort_order: 0 },
          { value: 'M', sort_order: 1 },
          { value: 'L', sort_order: 2 },
          { value: 'XL', sort_order: 3 },
        ],
      },
    ],
    variants: [
      { id: 'v-001-blk-s', product_id: 'prod-001', sku: 'VL-W01-BS', combination: { Color: 'Obsidian Black', Size: 'S' }, stock: 12, is_active: true },
      { id: 'v-001-blk-m', product_id: 'prod-001', sku: 'VL-W01-BM', combination: { Color: 'Obsidian Black', Size: 'M' }, stock: 15, is_active: true },
      { id: 'v-001-blk-l', product_id: 'prod-001', sku: 'VL-W01-BL', combination: { Color: 'Obsidian Black', Size: 'L' }, stock: 8, is_active: true },
      { id: 'v-001-blk-xl', product_id: 'prod-001', sku: 'VL-W01-BXL', combination: { Color: 'Obsidian Black', Size: 'XL' }, stock: 5, is_active: true },
      { id: 'v-001-iv-s', product_id: 'prod-001', sku: 'VL-W01-IS', combination: { Color: 'Ivory Cream', Size: 'S' }, stock: 10, is_active: true },
      { id: 'v-001-iv-m', product_id: 'prod-001', sku: 'VL-W01-IM', combination: { Color: 'Ivory Cream', Size: 'M' }, stock: 14, is_active: true },
      { id: 'v-001-iv-l', product_id: 'prod-001', sku: 'VL-W01-IL', combination: { Color: 'Ivory Cream', Size: 'L' }, stock: 0, is_active: true },
    ],
    attributes: [
      { name: 'Gender', value: 'Women', is_filterable: true },
      { name: 'Fit', value: 'Oversized', is_filterable: true },
      { name: 'Material', value: 'Heavyweight Cotton', is_filterable: true },
    ],
  },
  {
    id: 'prod-002',
    name: 'Aero-Sculpt High-Waist Seamless Leggings',
    slug: 'aero-sculpt-high-waist-seamless-leggings',
    item_code: 'VL-W-0204',
    brand: 'VELORA',
    category_id: 'cat-women',
    subcategory_id: 'sub-w-leggings',
    description: 'Engineered with compressive 4-way stretch fabric and a seamless contour waistband for sculpting support during workouts or high-end athleisure styling.',
    item_details: '• 75% Nylon, 25% Spandex\n• Squat-proof ultra-dense knit\n• Moisture wicking with gold heat-seal logo\n• Hidden waist card pocket',
    normal_price_lkr: 6800,
    offer_price_lkr: 5900,
    stock: 35,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_best_seller: false,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Aero-Sculpt High-Waist Seamless Leggings',
        sort_order: 0,
        is_primary: true,
      },
      {
        image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Aero-Sculpt Leggings Fabric Detail',
        sort_order: 1,
        is_primary: false,
      },
    ],
    options: [
      {
        name: 'Color',
        sort_order: 0,
        values: [
          { value: 'Midnight Slate', sort_order: 0 },
          { value: 'Mocha Espresso', sort_order: 1 },
        ],
      },
      {
        name: 'Size',
        sort_order: 1,
        values: [
          { value: 'XS', sort_order: 0 },
          { value: 'S', sort_order: 1 },
          { value: 'M', sort_order: 2 },
          { value: 'L', sort_order: 3 },
        ],
      },
    ],
    variants: [
      { id: 'v-002-sl-s', product_id: 'prod-002', sku: 'VL-LEG-SLS', combination: { Color: 'Midnight Slate', Size: 'S' }, stock: 8, is_active: true },
      { id: 'v-002-sl-m', product_id: 'prod-002', sku: 'VL-LEG-SLM', combination: { Color: 'Midnight Slate', Size: 'M' }, stock: 12, is_active: true },
      { id: 'v-002-mo-s', product_id: 'prod-002', sku: 'VL-LEG-MOS', combination: { Color: 'Mocha Espresso', Size: 'S' }, stock: 6, is_active: true },
      { id: 'v-002-mo-m', product_id: 'prod-002', sku: 'VL-LEG-MOM', combination: { Color: 'Mocha Espresso', Size: 'M' }, stock: 9, is_active: true },
    ],
    attributes: [
      { name: 'Gender', value: 'Women', is_filterable: true },
      { name: 'Fit', value: 'Compression', is_filterable: true },
      { name: 'Condition', value: 'New', is_filterable: true },
    ],
  },
  {
    id: 'prod-003',
    name: 'Atelier Relaxed Heavy Terry Hoodie',
    slug: 'atelier-relaxed-heavy-terry-hoodie',
    item_code: 'VL-M-0301',
    brand: 'VELORA',
    category_id: 'cat-men',
    subcategory_id: 'sub-m-hoodies',
    description: 'Substantial 460GSM French terry construction with structured double-layer hood and minimal kangaroo pocket. Built for longevity and effortless street elegance.',
    item_details: '• 100% Organic French Terry Cotton (460 GSM)\n• Ribbed side gussets\n• Metal dipped drawstrings with embossed tip\n• Preshrunk for tailored drape',
    normal_price_lkr: 9800,
    offer_price_lkr: 8500,
    stock: 28,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_best_seller: true,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Atelier Relaxed Heavy Terry Hoodie in Jet Black',
        sort_order: 0,
        is_primary: true,
      },
      {
        image_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Hoodie Detail',
        sort_order: 1,
        is_primary: false,
      },
    ],
    options: [
      {
        name: 'Color',
        sort_order: 0,
        values: [
          { value: 'Washed Onyx', sort_order: 0 },
          { value: 'Heather Grey', sort_order: 1 },
        ],
      },
      {
        name: 'Size',
        sort_order: 1,
        values: [
          { value: 'M', sort_order: 0 },
          { value: 'L', sort_order: 1 },
          { value: 'XL', sort_order: 2 },
        ],
      },
    ],
    variants: [
      { id: 'v-003-ox-m', product_id: 'prod-003', sku: 'VL-HD-OXM', combination: { Color: 'Washed Onyx', Size: 'M' }, stock: 8, is_active: true },
      { id: 'v-003-ox-l', product_id: 'prod-003', sku: 'VL-HD-OXL', combination: { Color: 'Washed Onyx', Size: 'L' }, stock: 10, is_active: true },
      { id: 'v-003-ox-xl', product_id: 'prod-003', sku: 'VL-HD-OXXL', combination: { Color: 'Washed Onyx', Size: 'XL' }, stock: 4, is_active: true },
      { id: 'v-003-gr-m', product_id: 'prod-003', sku: 'VL-HD-GRM', combination: { Color: 'Heather Grey', Size: 'M' }, stock: 7, is_active: true },
    ],
    attributes: [
      { name: 'Gender', value: 'Men', is_filterable: true },
      { name: 'Fit', value: 'Relaxed', is_filterable: true },
      { name: 'Material', value: 'French Terry Cotton', is_filterable: true },
    ],
  },
  {
    id: 'prod-004',
    name: 'Solarium Titanium Aviator Sunglasses',
    slug: 'solarium-titanium-aviator-sunglasses',
    item_code: 'VL-EYE-401',
    brand: 'VELORA',
    category_id: 'cat-sunglasses',
    subcategory_id: 'sub-s-unisex',
    description: 'Precision Japanese titanium frame with polarized polarized nylon lenses offering 100% UVA/UVB protection and anti-reflective internal coating.',
    item_details: '• Aerospace-grade Titanium Frame\n• Polarized Category 3 UV400 Lenses\n• Laser etched Velora monogram\n• Includes magnetic leather hardcase & microfibre cloth',
    normal_price_lkr: 14500,
    offer_price_lkr: 12900,
    stock: 20,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_best_seller: true,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Solarium Titanium Aviator Sunglasses Gold/Black',
        sort_order: 0,
        is_primary: true,
      },
      {
        image_url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Solarium Sunglasses Case & Detail',
        sort_order: 1,
        is_primary: false,
      },
    ],
    options: [
      {
        name: 'Frame Color',
        sort_order: 0,
        values: [
          { value: 'Brushed Champagne Gold', sort_order: 0 },
          { value: 'Gunmetal Titanium', sort_order: 1 },
        ],
      },
      {
        name: 'Lens Color',
        sort_order: 1,
        values: [
          { value: 'Polarized Smoke Black', sort_order: 0 },
          { value: 'Gradient Warm Amber', sort_order: 1 },
        ],
      },
    ],
    variants: [
      { id: 'v-004-gold-smk', product_id: 'prod-004', sku: 'VL-SUN-GDSMK', combination: { 'Frame Color': 'Brushed Champagne Gold', 'Lens Color': 'Polarized Smoke Black' }, stock: 8, is_active: true },
      { id: 'v-004-gold-amb', product_id: 'prod-004', sku: 'VL-SUN-GDAMB', combination: { 'Frame Color': 'Brushed Champagne Gold', 'Lens Color': 'Gradient Warm Amber' }, stock: 6, is_active: true },
      { id: 'v-004-gun-smk', product_id: 'prod-004', sku: 'VL-SUN-GNSMK', combination: { 'Frame Color': 'Gunmetal Titanium', 'Lens Color': 'Polarized Smoke Black' }, stock: 6, is_active: true },
    ],
    attributes: [
      { name: 'Gender', value: 'Unisex', is_filterable: true },
      { name: 'Frame Style', value: 'Aviator', is_filterable: true },
      { name: 'Frame Material', value: 'Titanium', is_filterable: true },
      { name: 'Shape', value: 'Geometric Aviator', is_filterable: true },
      { name: 'Condition', value: 'New', is_filterable: true },
    ],
  },
  {
    id: 'prod-005',
    name: 'Nuit Dorée Eau de Parfum (100ml)',
    slug: 'nuit-doree-eau-de-parfum-100ml',
    item_code: 'VL-PRF-501',
    brand: 'VELORA',
    category_id: 'cat-perfumes',
    subcategory_id: 'sub-p-all',
    description: 'An intoxicating blend of saffron, Ceylon black tea, ambergris, and smoky bourbon vanilla. Developed exclusively by master perfumers in Grasse.',
    item_details: '• Concentration: Eau de Parfum (24% Extrait formulation)\n• Top: Saffron, Bergamot, Pink Peppercorn\n• Heart: Ceylon Black Tea, Damask Rose, Cedarwood\n• Base: Ambergris, Bourbon Vanilla, Oud Accord\n• Long-lasting 10-14 hour sillage',
    normal_price_lkr: 18500,
    offer_price_lkr: 16500,
    stock: 22,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_best_seller: true,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Nuit Dorée Eau de Parfum Luxury Bottle',
        sort_order: 0,
        is_primary: true,
      },
      {
        image_url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Perfume Box Packaging',
        sort_order: 1,
        is_primary: false,
      },
    ],
    options: [
      {
        name: 'Volume',
        sort_order: 0,
        values: [
          { value: '50ml', sort_order: 0 },
          { value: '100ml', sort_order: 1 },
        ],
      },
    ],
    variants: [
      { id: 'v-005-50', product_id: 'prod-005', sku: 'VL-PRF-50ML', combination: { Volume: '50ml' }, stock: 10, price_override_lkr: 11500, is_active: true },
      { id: 'v-005-100', product_id: 'prod-005', sku: 'VL-PRF-100ML', combination: { Volume: '100ml' }, stock: 12, price_override_lkr: 16500, is_active: true },
    ],
    attributes: [
      { name: 'Gender', value: 'Unisex', is_filterable: true },
      { name: 'Fragrance Family', value: 'Oriental Amber', is_filterable: true },
      { name: 'Condition', value: 'New', is_filterable: true },
    ],
  },
  {
    id: 'prod-006',
    name: 'Sovereign Minimalist Ceramic Chronograph Watch',
    slug: 'sovereign-minimalist-ceramic-chronograph-watch',
    item_code: 'VL-WCH-601',
    brand: 'VELORA',
    category_id: 'cat-watches',
    subcategory_id: 'sub-w-him',
    description: 'High-tech matte ceramic case with Swiss quartz movement, date complication, and a quick-release magnetic Milanese loop.',
    item_details: '• 40mm High-density Ceramic Casing\n• Anti-reflective Sapphire Crystal Glass\n• 5 ATM Water Resistance\n• 316L Stainless Steel Milanese Strap\n• 2 Year Manufacturer Warranty',
    normal_price_lkr: 24500,
    offer_price_lkr: 21000,
    stock: 14,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_best_seller: true,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Sovereign Minimalist Watch on Display',
        sort_order: 0,
        is_primary: true,
      },
      {
        image_url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Sovereign Watch Dial Close-Up',
        sort_order: 1,
        is_primary: false,
      },
    ],
    options: [
      {
        name: 'Dial Color',
        sort_order: 0,
        values: [
          { value: 'Matte Obsidian', sort_order: 0 },
          { value: 'Brushed Champagne', sort_order: 1 },
        ],
      },
    ],
    variants: [
      { id: 'v-006-blk', product_id: 'prod-006', sku: 'VL-WCH-BLK', combination: { 'Dial Color': 'Matte Obsidian' }, stock: 8, is_active: true },
      { id: 'v-006-gold', product_id: 'prod-006', sku: 'VL-WCH-GLD', combination: { 'Dial Color': 'Brushed Champagne' }, stock: 6, is_active: true },
    ],
    attributes: [
      { name: 'Gender', value: 'Men', is_filterable: true },
      { name: 'Movement', value: 'Swiss Quartz', is_filterable: true },
      { name: 'Material', value: 'Ceramic & Sapphire', is_filterable: true },
    ],
  },
  {
    id: 'prod-007',
    name: 'Luminesce Botanical Radiance Face Serum (50ml)',
    slug: 'luminesce-botanical-radiance-face-serum-50ml',
    item_code: 'VL-COS-701',
    brand: 'VELORA',
    category_id: 'cat-cosmetics',
    subcategory_id: 'sub-c-face',
    description: 'Infused with cold-pressed moringa oil, 15% stabilised Vitamin C, and Ceylon green tea catechins. Restores radiant skin glow and cellular hydration.',
    item_details: '• 15% Ethyl Ascorbic Acid + Ferulic Acid\n• Hyaluronic Acid multi-molecular complex\n• Cruelty-free & Paraben-free\n• Dermatologist tested for all tropical skin types',
    normal_price_lkr: 4800,
    offer_price_lkr: 3950,
    stock: 30,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_best_seller: true,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Luminesce Botanical Radiance Face Serum Dropper',
        sort_order: 0,
        is_primary: true,
      },
    ],
    options: [],
    variants: [],
    attributes: [
      { name: 'Gender', value: 'Unisex', is_filterable: true },
      { name: 'Skin Type', value: 'All Skin Types', is_filterable: true },
      { name: 'Volume', value: '50ml', is_filterable: true },
    ],
  },
  {
    id: 'prod-008',
    name: 'Velora Monogram Heavy Duffel Gym & Travel Bag',
    slug: 'velora-monogram-heavy-duffel-gym-travel-bag',
    item_code: 'VL-ACC-801',
    brand: 'VELORA',
    category_id: 'cat-accessories',
    subcategory_id: 'sub-a-bags',
    description: 'Weather-resistant ballistic nylon with waterproof zippers, ventilated dedicated shoe compartment, and padded shoulder strap.',
    item_details: '• 45L Capacity\n• High-grade 900D Ballistic Nylon\n• Separate isolated sneaker sleeve\n• Gold hardware & metal feet',
    normal_price_lkr: 8900,
    offer_price_lkr: 7500,
    stock: 18,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_best_seller: false,
    is_demo: true,
    images: [
      {
        image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop',
        thumbnail_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=400&auto=format&fit=crop',
        alt_text: 'Velora Heavy Duffel Bag in Matte Black',
        sort_order: 0,
        is_primary: true,
      },
    ],
    options: [],
    variants: [],
    attributes: [
      { name: 'Gender', value: 'Unisex', is_filterable: true },
      { name: 'Material', value: 'Ballistic Nylon', is_filterable: true },
    ],
  },
];
